import type { ComponentType, SVGProps } from "react";

import {
  IconAlarm,
  IconAnchor,
  IconApple,
  IconArchive,
  IconAtom,
  IconBabyCarriage,
  IconBackpack,
  IconBallBasketball,
  IconBallBaseball,
  IconBallFootball,
  IconBallTennis,
  IconBallVolleyball,
  IconBalloon,
  IconBed,
  IconBell,
  IconBolt,
  IconBook,
  IconBookmark,
  IconBriefcase,
  IconBuilding,
  IconBulb,
  IconBurger,
  IconBus,
  IconButterfly,
  IconCake,
  IconCalendar,
  IconCamera,
  IconCandy,
  IconCar,
  IconCarrot,
  IconCash,
  IconCat,
  IconChartBar,
  IconChartLine,
  IconCheese,
  IconChefHat,
  IconCherry,
  IconChess,
  IconChristmasTree,
  IconClipboard,
  IconClock,
  IconCloud,
  IconCode,
  IconCoffee,
  IconCoin,
  IconCompass,
  IconConfetti,
  IconCookie,
  IconCreditCard,
  IconCrown,
  IconCup,
  IconDatabase,
  IconDeer,
  IconDeviceLaptop,
  IconDeviceMobile,
  IconDeviceTv,
  IconDeviceWatch,
  IconDevices,
  IconDiamond,
  IconDice,
  IconDna,
  IconDog,
  IconDoor,
  IconDownload,
  IconDrone,
  IconDroplet,
  IconEdit,
  IconEgg,
  IconEye,
  IconFeather,
  IconFile,
  IconFireExtinguisher,
  IconFish,
  IconFlag,
  IconFlame,
  IconFlask,
  IconFlower,
  IconFolder,
  IconGhost,
  IconGift,
  IconGlobe,
  IconGuitarPick,
  IconHammer,
  IconHeadphones,
  IconHeart,
  IconHome,
  IconHorse,
  IconHourglass,
  IconIceCream,
  IconInbox,
  IconInfinity,
  IconKey,
  IconKeyboard,
  IconLeaf,
  IconLemon,
  IconLifebuoy,
  IconLighter,
  IconLink,
  IconLock,
  IconLuggage,
  IconMagnet,
  IconMail,
  IconMap,
  IconMeat,
  IconMessage,
  IconMicrophone,
  IconMicroscope,
  IconMilk,
  IconMoodSmile,
  IconMoon,
  IconMotorbike,
  IconMountain,
  IconMug,
  IconMusic,
  IconNews,
  IconNotebook,
  IconPackage,
  IconPaint,
  IconPalette,
  IconPaperBag,
  IconPaperclip,
  IconParachute,
  IconPaw,
  IconPencil,
  IconPepper,
  IconPhone,
  IconPhoto,
  IconPiano,
  IconPig,
  IconPin,
  IconPizza,
  IconPlane,
  IconPlanet,
  IconPlant,
  IconPlant2,
  IconPlug,
  IconPodium,
  IconPolaroid,
  IconPresentation,
  IconPrinter,
  IconPuzzle,
  IconQrcode,
  IconRainbow,
  IconRefresh,
  IconRoad,
  IconRobot,
  IconRocket,
  IconRuler,
  IconSailboat,
  IconSalad,
  IconSchool,
  IconSchoolBell,
  IconScissors,
  IconSearch,
  IconServer,
  IconSettings,
  IconShield,
  IconShip,
  IconShirt,
  IconShoppingBag,
  IconShoppingCart,
  IconSnowflake,
  IconSofa,
  IconSoup,
  IconSparkles,
  IconSpeakerphone,
  IconSpray,
  IconStar,
  IconStethoscope,
  IconSticker,
  IconSun,
  IconSunglasses,
  IconSunrise,
  IconSwimming,
  IconSword,
  IconTable,
  IconTag,
  IconTarget,
  IconTeapot,
  IconTelescope,
  IconTerminal,
  IconThermometer,
  IconThumbUp,
  IconTicket,
  IconTools,
  IconTrain,
  IconTree,
  IconTrophy,
  IconTruck,
  IconUfo,
  IconUmbrella,
  IconUser,
  IconUsers,
  IconVideo,
  IconVolume,
  IconWallet,
  IconWifi,
  IconWind,
  IconWorld,
  IconYinYang,
  IconYoga,
  IconZoomIn,
} from "@tabler/icons-react";

export type TablerIconComponent = ComponentType<
  SVGProps<SVGSVGElement> & { size?: number | string; stroke?: number }
>;

/**
 * Curated, flat Tabler icon catalog used by the link icon picker.
 * Keys are stored in the DB as `t:<key>` (e.g. `t:rocket`).
 */
export const TABLER_ICONS: Record<string, TablerIconComponent> = {
  rocket: IconRocket,
  heart: IconHeart,
  star: IconStar,
  bolt: IconBolt,
  bulb: IconBulb,
  sparkles: IconSparkles,
  flame: IconFlame,
  "fire-extinguisher": IconFireExtinguisher,
  rainbow: IconRainbow,
  infinity: IconInfinity,
  diamond: IconDiamond,
  crown: IconCrown,
  trophy: IconTrophy,
  target: IconTarget,
  flag: IconFlag,
  bookmark: IconBookmark,
  pin: IconPin,
  link: IconLink,
  world: IconWorld,
  globe: IconGlobe,
  search: IconSearch,
  eye: IconEye,
  key: IconKey,
  lock: IconLock,
  shield: IconShield,
  ghost: IconGhost,
  ufo: IconUfo,
  robot: IconRobot,
  atom: IconAtom,
  dna: IconDna,
  "yin-yang": IconYinYang,
  confetti: IconConfetti,
  sticker: IconSticker,
  balloon: IconBalloon,
  gift: IconGift,
  "christmas-tree": IconChristmasTree,
  // people / mood
  user: IconUser,
  users: IconUsers,
  smile: IconMoodSmile,
  baby: IconBabyCarriage,
  // animals & nature
  cat: IconCat,
  dog: IconDog,
  paw: IconPaw,
  fish: IconFish,
  deer: IconDeer,
  horse: IconHorse,
  pig: IconPig,
  butterfly: IconButterfly,
  feather: IconFeather,
  leaf: IconLeaf,
  plant: IconPlant,
  plant2: IconPlant2,
  tree: IconTree,
  flower: IconFlower,
  mountain: IconMountain,
  // weather
  sun: IconSun,
  moon: IconMoon,
  sunrise: IconSunrise,
  cloud: IconCloud,
  snowflake: IconSnowflake,
  wind: IconWind,
  droplet: IconDroplet,
  // food & drink
  apple: IconApple,
  cake: IconCake,
  candy: IconCandy,
  cookie: IconCookie,
  carrot: IconCarrot,
  cheese: IconCheese,
  "chef-hat": IconChefHat,
  cherry: IconCherry,
  egg: IconEgg,
  lemon: IconLemon,
  meat: IconMeat,
  pepper: IconPepper,
  salad: IconSalad,
  soup: IconSoup,
  pizza: IconPizza,
  burger: IconBurger,
  "ice-cream": IconIceCream,
  milk: IconMilk,
  mug: IconMug,
  cup: IconCup,
  coffee: IconCoffee,
  teapot: IconTeapot,
  // sports & activity
  basketball: IconBallBasketball,
  football: IconBallFootball,
  tennis: IconBallTennis,
  volleyball: IconBallVolleyball,
  baseball: IconBallBaseball,
  swimming: IconSwimming,
  yoga: IconYoga,
  chess: IconChess,
  dice: IconDice,
  // travel & transport
  plane: IconPlane,
  train: IconTrain,
  car: IconCar,
  motorbike: IconMotorbike,
  ship: IconShip,
  sailboat: IconSailboat,
  bus: IconBus,
  truck: IconTruck,
  road: IconRoad,
  anchor: IconAnchor,
  parachute: IconParachute,
  drone: IconDrone,
  luggage: IconLuggage,
  backpack: IconBackpack,
  // shopping & money
  "shopping-bag": IconShoppingBag,
  "shopping-cart": IconShoppingCart,
  "paper-bag": IconPaperBag,
  tag: IconTag,
  ticket: IconTicket,
  "credit-card": IconCreditCard,
  wallet: IconWallet,
  coin: IconCoin,
  cash: IconCash,
  package: IconPackage,
  // tools & art
  hammer: IconHammer,
  tools: IconTools,
  scissors: IconScissors,
  ruler: IconRuler,
  paint: IconPaint,
  palette: IconPalette,
  spray: IconSpray,
  magnet: IconMagnet,
  flask: IconFlask,
  microscope: IconMicroscope,
  telescope: IconTelescope,
  compass: IconCompass,
  map: IconMap,
  // building & home
  home: IconHome,
  building: IconBuilding,
  school: IconSchool,
  door: IconDoor,
  bed: IconBed,
  sofa: IconSofa,
  table: IconTable,
  // devices & tech
  laptop: IconDeviceLaptop,
  mobile: IconDeviceMobile,
  tv: IconDeviceTv,
  watch: IconDeviceWatch,
  devices: IconDevices,
  camera: IconCamera,
  photo: IconPhoto,
  video: IconVideo,
  qrcode: IconQrcode,
  keyboard: IconKeyboard,
  server: IconServer,
  database: IconDatabase,
  terminal: IconTerminal,
  code: IconCode,
  printer: IconPrinter,
  plug: IconPlug,
  wifi: IconWifi,
  // productivity & office
  calendar: IconCalendar,
  clock: IconClock,
  alarm: IconAlarm,
  hourglass: IconHourglass,
  briefcase: IconBriefcase,
  folder: IconFolder,
  file: IconFile,
  notebook: IconNotebook,
  book: IconBook,
  pencil: IconPencil,
  edit: IconEdit,
  clipboard: IconClipboard,
  paperclip: IconPaperclip,
  archive: IconArchive,
  inbox: IconInbox,
  news: IconNews,
  presentation: IconPresentation,
  podium: IconPodium,
  polaroid: IconPolaroid,
  // music & comms
  music: IconMusic,
  microphone: IconMicrophone,
  headphones: IconHeadphones,
  speakerphone: IconSpeakerphone,
  piano: IconPiano,
  "guitar-pick": IconGuitarPick,
  bell: IconBell,
  "school-bell": IconSchoolBell,
  message: IconMessage,
  mail: IconMail,
  phone: IconPhone,
  volume: IconVolume,
  // health & misc
  stethoscope: IconStethoscope,
  thermometer: IconThermometer,
  lifebuoy: IconLifebuoy,
  lighter: IconLighter,
  sword: IconSword,
  shirt: IconShirt,
  sunglasses: IconSunglasses,
  umbrella: IconUmbrella,
  "thumb-up": IconThumbUp,
  puzzle: IconPuzzle,
  planet: IconPlanet,
  // chart & ui
  "chart-bar": IconChartBar,
  "chart-line": IconChartLine,
  download: IconDownload,
  refresh: IconRefresh,
  settings: IconSettings,
  "zoom-in": IconZoomIn,
};

export const TABLER_ICON_KEYS = Object.keys(TABLER_ICONS);

/**
 * Persian search aliases for common icons. Allows users to find icons by
 * typing the Farsi term (e.g. "سگ" → dog). Each entry maps a Tabler key
 * (without the `t:` prefix) to one or more Persian search tokens.
 */
export const TABLER_ICON_ALIASES: Record<string, string> = {
  alarm: "ساعت زنگدار آلارم",
  anchor: "لنگر کشتی",
  apple: "سیب میوه",
  archive: "آرشیو بایگانی",
  atom: "اتم علم",
  "baby-carriage": "کالسکه بچه نوزاد",
  backpack: "کوله پشتی",
  "ball-basketball": "بسکتبال توپ",
  "ball-baseball": "بیسبال توپ",
  "ball-football": "فوتبال توپ",
  "ball-tennis": "تنیس توپ",
  "ball-volleyball": "والیبال توپ",
  balloon: "بادکنک",
  bed: "تخت خواب",
  bell: "زنگ ناقوس",
  bolt: "برق صاعقه رعد",
  book: "کتاب",
  bookmark: "نشان نشانک",
  briefcase: "کیف اداری",
  building: "ساختمان",
  bulb: "لامپ ایده",
  burger: "برگر همبرگر",
  bus: "اتوبوس",
  butterfly: "پروانه",
  cake: "کیک تولد",
  calendar: "تقویم",
  camera: "دوربین",
  candy: "آب نبات",
  car: "ماشین خودرو اتومبیل",
  carrot: "هویج",
  cash: "پول نقد",
  cat: "گربه",
  "chart-bar": "نمودار میله ای",
  "chart-line": "نمودار خطی",
  cheese: "پنیر",
  "chef-hat": "آشپز کلاه",
  cherry: "گیلاس آلبالو",
  chess: "شطرنج",
  "christmas-tree": "درخت کریسمس",
  clipboard: "کلیپبورد",
  clock: "ساعت",
  cloud: "ابر",
  code: "کد برنامه نویسی",
  coffee: "قهوه",
  coin: "سکه پول",
  compass: "قطب نما",
  confetti: "جشن کاغذ رنگی",
  cookie: "کوکی شیرینی",
  "credit-card": "کارت اعتباری بانکی",
  crown: "تاج پادشاه",
  cup: "فنجان لیوان",
  database: "پایگاه داده",
  deer: "گوزن",
  "device-laptop": "لپ تاپ",
  "device-mobile": "موبایل گوشی",
  "device-tv": "تلویزیون",
  "device-watch": "ساعت مچی",
  diamond: "الماس جواهر",
  dog: "سگ",
  donut: "دونات",
  download: "دانلود",
  drone: "پهپاد",
  edit: "ویرایش",
  egg: "تخم مرغ",
  "fire-extinguisher": "کپسول آتش نشانی",
  fire: "آتش شعله",
  fish: "ماهی",
  flag: "پرچم",
  flame: "آتش شعله",
  flask: "بشر آزمایش",
  flower: "گل",
  gift: "هدیه کادو",
  globe: "کره زمین جهان",
  glass: "لیوان نوشیدنی",
  grill: "کباب پز",
  "guitar-pick": "گیتار مضراب",
  hammer: "چکش",
  hanger: "چوب لباسی",
  headphones: "هدفون",
  heart: "قلب عشق",
  helmet: "کلاه ایمنی",
  home: "خانه منزل",
  horseshoe: "نعل اسب",
  hotel: "هتل",
  "ice-cream": "بستنی",
  inbox: "اینباکس صندوق ورودی",
  jacket: "ژاکت کاپشن",
  key: "کلید",
  knife: "چاقو",
  laptop: "لپ تاپ",
  leaf: "برگ",
  lifebuoy: "نجات غریق حلقه",
  lighter: "فندک",
  lock: "قفل",
  mail: "ایمیل نامه پست",
  map: "نقشه",
  message: "پیام چت",
  microphone: "میکروفون",
  moon: "ماه شب",
  motorbike: "موتور سیکلت",
  mountain: "کوه",
  mouse: "موس",
  music: "موسیقی آهنگ",
  "map-pin": "پین نقشه مکان",
  news: "خبر روزنامه",
  notebook: "دفترچه دفتر",
  package: "بسته",
  paint: "نقاشی رنگ",
  paperclip: "گیره کاغذ",
  pencil: "مداد",
  phone: "تلفن تماس",
  piano: "پیانو",
  "pin-map": "پین نقشه",
  pizza: "پیتزا",
  plane: "هواپیما",
  planet: "سیاره",
  plant: "گیاه",
  podium: "سکو",
  polaroid: "پلاروید عکس",
  presentation: "ارائه پرزنتیشن",
  printer: "پرینتر چاپگر",
  puzzle: "پازل",
  refresh: "بروزرسانی",
  rocket: "موشک راکت",
  rose: "گل رز",
  scissors: "قیچی",
  "school-bell": "زنگ مدرسه",
  search: "جستجو سرچ",
  settings: "تنظیمات",
  shield: "سپر",
  ship: "کشتی",
  shirt: "پیراهن لباس",
  shoe: "کفش",
  shopping: "خرید فروشگاه",
  "shopping-bag": "کیف خرید فروشگاه",
  "shopping-cart": "سبد خرید",
  smile: "لبخند خنده",
  snowflake: "دانه برف",
  speakerphone: "بلندگو",
  star: "ستاره",
  stethoscope: "گوشی پزشکی",
  sun: "خورشید آفتاب",
  sunglasses: "عینک آفتابی",
  sushi: "سوشی",
  sword: "شمشیر",
  "tea-bag": "چای",
  "thumb-up": "لایک پسند",
  thermometer: "دماسنج",
  tools: "ابزار",
  truck: "کامیون",
  trophy: "جام قهرمانی",
  umbrella: "چتر",
  user: "کاربر شخص نفر",
  users: "کاربران مردم",
  video: "ویدیو فیلم",
  volume: "صدا بلندی",
  wallet: "کیف پول",
  whirl: "گردباد",
  "wind-turbine": "توربین بادی",
  wine: "شراب",
  yoga: "یوگا",
  "zoom-in": "زوم بزرگنمایی",
};

const TABLER_PREFIX = "t:";

export function isTablerIconKey(value: unknown): value is string {
  return (
    typeof value === "string" &&
    value.startsWith(TABLER_PREFIX) &&
    value.slice(TABLER_PREFIX.length) in TABLER_ICONS
  );
}

export function tablerKeyOf(name: string): string {
  return `${TABLER_PREFIX}${name}`;
}

export function tablerNameOf(key: string): string | null {
  if (!key.startsWith(TABLER_PREFIX)) return null;
  return key.slice(TABLER_PREFIX.length);
}

export function getTablerIcon(key: string): TablerIconComponent | null {
  const name = tablerNameOf(key);
  if (!name) return null;
  return TABLER_ICONS[name] ?? null;
}
