import type { ComponentType, SVGProps } from "react";

import {
  IconAlarm,
  IconAnchor,
  IconApple,
  IconArchive,
  IconAtom,
  IconBabyCarriage,
  IconBackpack,
  IconBallBasketball,
  IconBallBaseball,
  IconBallFootball,
  IconBallTennis,
  IconBallVolleyball,
  IconBalloon,
  IconBed,
  IconBell,
  IconBolt,
  IconBook,
  IconBookmark,
  IconBriefcase,
  IconBuilding,
  IconBulb,
  IconBurger,
  IconBus,
  IconButterfly,
  IconCake,
  IconCalendar,
  IconCamera,
  IconCandy,
  IconCar,
  IconCarrot,
  IconCash,
  IconCat,
  IconChartBar,
  IconChartLine,
  IconCheese,
  IconChefHat,
  IconCherry,
  IconChess,
  IconChristmasTree,
  IconClipboard,
  IconClock,
  IconCloud,
  IconCode,
  IconCoffee,
  IconCoin,
  IconCompass,
  IconConfetti,
  IconCookie,
  IconCreditCard,
  IconCrown,
  IconCup,
  IconDatabase,
  IconDeer,
  IconDeviceLaptop,
  IconDeviceMobile,
  IconDeviceTv,
  IconDeviceWatch,
  IconDevices,
  IconDiamond,
  IconDice,
  IconDna,
  IconDog,
  IconDoor,
  IconDownload,
  IconDrone,
  IconDroplet,
  IconEdit,
  IconEgg,
  IconEye,
  IconFeather,
  IconFile,
  IconFireExtinguisher,
  IconFish,
  IconFlag,
  IconFlame,
  IconFlask,
  IconFlower,
  IconFolder,
  IconGhost,
  IconGift,
  IconGlobe,
  IconGuitarPick,
  IconHammer,
  IconHeadphones,
  IconHeart,
  IconHome,
  IconHorse,
  IconHourglass,
  IconIceCream,
  IconInbox,
  IconInfinity,
  IconKey,
  IconKeyboard,
  IconLeaf,
  IconLemon,
  IconLifebuoy,
  IconLighter,
  IconLink,
  IconLock,
  IconLuggage,
  IconMagnet,
  IconMail,
  IconMap,
  IconMeat,
  IconMessage,
  IconMicrophone,
  IconMicroscope,
  IconMilk,
  IconMoodSmile,
  IconMoon,
  IconMotorbike,
  IconMountain,
  IconMug,
  IconMusic,
  IconNews,
  IconNotebook,
  IconPackage,
  IconPaint,
  IconPalette,
  IconPaperBag,
  IconPaperclip,
  IconParachute,
  IconPaw,
  IconPencil,
  IconPepper,
  IconPhone,
  IconPhoto,
  IconPiano,
  IconPig,
  IconPin,
  IconPizza,
  IconPlane,
  IconPlanet,
  IconPlant,
  IconPlant2,
  IconPlug,
  IconPodium,
  IconPolaroid,
  IconPresentation,
  IconPrinter,
  IconPuzzle,
  IconQrcode,
  IconRainbow,
  IconRefresh,
  IconRoad,
  IconRobot,
  IconRocket,
  IconRuler,
  IconSailboat,
  IconSalad,
  IconSchool,
  IconSchoolBell,
  IconScissors,
  IconSearch,
  IconServer,
  IconSettings,
  IconShield,
  IconShip,
  IconShirt,
  IconShoppingBag,
  IconShoppingCart,
  IconSnowflake,
  IconSofa,
  IconSoup,
  IconSparkles,
  IconSpeakerphone,
  IconSpray,
  IconStar,
  IconStethoscope,
  IconSticker,
  IconSun,
  IconSunglasses,
  IconSunrise,
  IconSwimming,
  IconSword,
  IconTable,
  IconTag,
  IconTarget,
  IconTeapot,
  IconTelescope,
  IconTerminal,
  IconThermometer,
  IconThumbUp,
  IconTicket,
  IconTools,
  IconTrain,
  IconTree,
  IconTrophy,
  IconTruck,
  IconUfo,
  IconUmbrella,
  IconUser,
  IconUsers,
  IconVideo,
  IconVolume,
  IconWallet,
  IconWifi,
  IconWind,
  IconWorld,
  IconYinYang,
  IconYoga,
  IconZoomIn,
  IconAccessible,
  IconActivity,
  IconActivityHeartbeat,
  IconAerialLift,
  IconAirBalloon,
  IconAirTrafficControl,
  IconAlien,
  IconAmbulance,
  IconAtom2,
  IconAutomaticGearbox,
  IconAvocado,
  IconBabyBottle,
  IconBackhoe,
  IconBaguette,
  IconBandage,
  IconBasket,
  IconBasketBolt,
  IconBasketCancel,
  IconBasketCheck,
  IconBasketCode,
  IconBasketCog,
  IconBasketDiscount,
  IconBasketDollar,
  IconBasketDown,
  IconBasketExclamation,
  IconBasketHeart,
  IconBasketMinus,
  IconBasketPause,
  IconBasketPin,
  IconBasketPlus,
  IconBasketQuestion,
  IconBasketSearch,
  IconBasketShare,
  IconBasketStar,
  IconBasketUp,
  IconBasketX,
  IconBat,
  IconBatteryAutomotive,
  IconBeach,
  IconBeer,
  IconBike,
  IconBlind,
  IconBone,
  IconBottle,
  IconBowl,
  IconBowlChopsticks,
  IconBowlSpoon,
  IconBraille,
  IconBrain,
  IconBread,
  IconBubbleTea,
  IconBubbleTea2,
  IconBulldozer,
  IconBusStop,
  IconBusinessplan,
  IconCactus,
  IconCakeRoll,
  IconCamper,
  IconCampfire,
  IconCane,
  IconCannabis,
  IconCar4wd,
  IconCarCrane,
  IconCarCrash,
  IconCarFan,
  IconCarFan1,
  IconCarFan2,
  IconCarFan3,
  IconCarFanAuto,
  IconCarOffRoad,
  IconCarSuspension,
  IconCarSuv,
  IconCarTurbine,
  IconCarambola,
  IconCaravan,
  IconCashBanknote,
  IconCashBanknoteEdit,
  IconCashBanknoteHeart,
  IconCashBanknoteMinus,
  IconCashBanknoteMove,
  IconCashBanknoteMoveBack,
  IconCashBanknotePlus,
  IconCashEdit,
  IconCashHeart,
  IconCashMinus,
  IconCashMove,
  IconCashMoveBack,
  IconCashPlus,
  IconCashRegister,
  IconChargingPile,
  IconCheckupList,
  IconClothesRack,
  IconCloudBolt,
  IconCloudCancel,
  IconCloudCheck,
  IconCloudCode,
  IconCloudCog,
  IconCloudDollar,
  IconCloudDown,
  IconCloudExclamation,
  IconCloudFog,
  IconCloudHeart,
  IconCloudMinus,
  IconCloudPause,
  IconCloudPin,
  IconCloudPlus,
  IconCloudQuestion,
  IconCloudRain,
  IconCloudSearch,
  IconCloudShare,
  IconCloudSnow,
  IconCloudStar,
  IconCloudStorm,
  IconCloudUp,
  IconCloudX,
  IconClover,
  IconClover2,
  IconCoinBitcoin,
  IconCoinEuro,
  IconCoinMonero,
  IconCoinPound,
  IconCoinRupee,
  IconCoinTaka,
  IconCoinYen,
  IconCoinYuan,
  IconCoins,
  IconComet,
  IconCooker,
  IconCrane,
  IconCreditCardHand,
  IconCreditCardPay,
  IconCreditCardRefund,
  IconCrutches,
  IconCrystalBall,
  IconCurrentLocation,
  IconDeaf,
  IconDental,
  IconDiaper,
  IconDirections,
  IconDisabled,
  IconDisabled2,
  IconDiscount,
  IconDna2,
  IconDogBowl,
  IconDropCircle,
  IconDroplets,
  IconDumpling,
  IconEPassport,
  IconEar,
  IconEggCracked,
  IconEggFried,
  IconEggs,
  IconEmergencyBed,
  IconEmpathize,
  IconEngine,
  IconEscalator,
  IconEscalatorDown,
  IconEscalatorUp,
  IconEyeBitcoin,
  IconEyeDiscount,
  IconEyeDotted,
  IconEyeTable,
  IconEyeglass,
  IconEyeglass2,
  IconFaceMask,
  IconFall,
  IconFerry,
  IconFingerprintScan,
  IconFireHydrant,
  IconFiretruck,
  IconFirstAidKit,
  IconFishBone,
  IconFishHook,
  IconFlag2,
  IconFlag3,
  IconFlagBolt,
  IconFlagCancel,
  IconFlagCheck,
  IconFlagCode,
  IconFlagCog,
  IconFlagDollar,
  IconFlagDown,
  IconFlagExclamation,
  IconFlagHeart,
  IconFlagMinus,
  IconFlagPause,
  IconFlagPin,
  IconFlagPlus,
  IconFlagQuestion,
  IconFlare,
  IconFlipFlops,
  IconForklift,
  IconGardenCart,
  IconGasStation,
  IconGiftCard,
  IconGlass,
  IconGlassChampagne,
  IconGlassCocktail,
  IconGlassFull,
  IconGlassGin,
  IconGrill,
  IconGrillFork,
  IconGrillSpatula,
  IconGrowth,
  IconHanger,
  IconHelicopter,
  IconHelicopterLanding,
  IconHorseshoe,
  IconIceCream2,
  IconIceberg,
  IconJacket,
  IconJetski,
  IconLeaf2,
  IconLemon2,
  IconLollipop,
  IconMelon,
  IconMeteor,
  IconMichelinBibGourmand,
  IconMichelinStar,
  IconMichelinStarGreen,
  IconMicrowave,
  IconMilkshake,
  IconMoneybag,
  IconMoneybagEdit,
  IconMoneybagHeart,
  IconMoneybagMinus,
  IconMoneybagMove,
  IconMoneybagMoveBack,
  IconMoneybagPlus,
  IconMoped,
  IconMushroom,
  IconNut,
  IconPerfume,
  IconPigMoney,
  IconReceiptBitcoin,
  IconReceiptEuro,
  IconReceiptPound,
  IconReceiptRupee,
  IconReceiptYen,
  IconReceiptYuan,
  IconRipple,
  IconSalt,
  IconSausage,
  IconSeedling,
  IconSnowman,
  IconSpider,
  IconSunElectricity,
  IconToolsKitchen,
  IconToolsKitchen2,
  IconToolsKitchen3,
  IconWheat,
  IconWhisk,
  IconWindElectricity,
} from "@tabler/icons-react";

export type TablerIconComponent = ComponentType<
  SVGProps<SVGSVGElement> & { size?: number | string; stroke?: number }
>;

/**
 * Curated, flat Tabler icon catalog used by the link icon picker.
 * Keys are stored in the DB as `t:<key>` (e.g. `t:rocket`).
 */
export const TABLER_ICONS: Record<string, TablerIconComponent> = {
  rocket: IconRocket,
  heart: IconHeart,
  star: IconStar,
  bolt: IconBolt,
  bulb: IconBulb,
  sparkles: IconSparkles,
  flame: IconFlame,
  "fire-extinguisher": IconFireExtinguisher,
  rainbow: IconRainbow,
  infinity: IconInfinity,
  diamond: IconDiamond,
  crown: IconCrown,
  trophy: IconTrophy,
  target: IconTarget,
  flag: IconFlag,
  bookmark: IconBookmark,
  pin: IconPin,
  link: IconLink,
  world: IconWorld,
  globe: IconGlobe,
  search: IconSearch,
  eye: IconEye,
  key: IconKey,
  lock: IconLock,
  shield: IconShield,
  ghost: IconGhost,
  ufo: IconUfo,
  robot: IconRobot,
  atom: IconAtom,
  dna: IconDna,
  "yin-yang": IconYinYang,
  confetti: IconConfetti,
  sticker: IconSticker,
  balloon: IconBalloon,
  gift: IconGift,
  "christmas-tree": IconChristmasTree,
  // people / mood
  user: IconUser,
  users: IconUsers,
  smile: IconMoodSmile,
  baby: IconBabyCarriage,
  // animals & nature
  cat: IconCat,
  dog: IconDog,
  paw: IconPaw,
  fish: IconFish,
  deer: IconDeer,
  horse: IconHorse,
  pig: IconPig,
  butterfly: IconButterfly,
  feather: IconFeather,
  leaf: IconLeaf,
  plant: IconPlant,
  plant2: IconPlant2,
  tree: IconTree,
  flower: IconFlower,
  mountain: IconMountain,
  // weather
  sun: IconSun,
  moon: IconMoon,
  sunrise: IconSunrise,
  cloud: IconCloud,
  snowflake: IconSnowflake,
  wind: IconWind,
  droplet: IconDroplet,
  // food & drink
  apple: IconApple,
  cake: IconCake,
  candy: IconCandy,
  cookie: IconCookie,
  carrot: IconCarrot,
  cheese: IconCheese,
  "chef-hat": IconChefHat,
  cherry: IconCherry,
  egg: IconEgg,
  lemon: IconLemon,
  meat: IconMeat,
  pepper: IconPepper,
  salad: IconSalad,
  soup: IconSoup,
  pizza: IconPizza,
  burger: IconBurger,
  "ice-cream": IconIceCream,
  milk: IconMilk,
  mug: IconMug,
  cup: IconCup,
  coffee: IconCoffee,
  teapot: IconTeapot,
  // sports & activity
  basketball: IconBallBasketball,
  football: IconBallFootball,
  tennis: IconBallTennis,
  volleyball: IconBallVolleyball,
  baseball: IconBallBaseball,
  swimming: IconSwimming,
  yoga: IconYoga,
  chess: IconChess,
  dice: IconDice,
  // travel & transport
  plane: IconPlane,
  train: IconTrain,
  car: IconCar,
  motorbike: IconMotorbike,
  ship: IconShip,
  sailboat: IconSailboat,
  bus: IconBus,
  truck: IconTruck,
  road: IconRoad,
  anchor: IconAnchor,
  parachute: IconParachute,
  drone: IconDrone,
  luggage: IconLuggage,
  backpack: IconBackpack,
  // shopping & money
  "shopping-bag": IconShoppingBag,
  "shopping-cart": IconShoppingCart,
  "paper-bag": IconPaperBag,
  tag: IconTag,
  ticket: IconTicket,
  "credit-card": IconCreditCard,
  wallet: IconWallet,
  coin: IconCoin,
  cash: IconCash,
  package: IconPackage,
  // tools & art
  hammer: IconHammer,
  tools: IconTools,
  scissors: IconScissors,
  ruler: IconRuler,
  paint: IconPaint,
  palette: IconPalette,
  spray: IconSpray,
  magnet: IconMagnet,
  flask: IconFlask,
  microscope: IconMicroscope,
  telescope: IconTelescope,
  compass: IconCompass,
  map: IconMap,
  // building & home
  home: IconHome,
  building: IconBuilding,
  school: IconSchool,
  door: IconDoor,
  bed: IconBed,
  sofa: IconSofa,
  table: IconTable,
  // devices & tech
  laptop: IconDeviceLaptop,
  mobile: IconDeviceMobile,
  tv: IconDeviceTv,
  watch: IconDeviceWatch,
  devices: IconDevices,
  camera: IconCamera,
  photo: IconPhoto,
  video: IconVideo,
  qrcode: IconQrcode,
  keyboard: IconKeyboard,
  server: IconServer,
  database: IconDatabase,
  terminal: IconTerminal,
  code: IconCode,
  printer: IconPrinter,
  plug: IconPlug,
  wifi: IconWifi,
  // productivity & office
  calendar: IconCalendar,
  clock: IconClock,
  alarm: IconAlarm,
  hourglass: IconHourglass,
  briefcase: IconBriefcase,
  folder: IconFolder,
  file: IconFile,
  notebook: IconNotebook,
  book: IconBook,
  pencil: IconPencil,
  edit: IconEdit,
  clipboard: IconClipboard,
  paperclip: IconPaperclip,
  archive: IconArchive,
  inbox: IconInbox,
  news: IconNews,
  presentation: IconPresentation,
  podium: IconPodium,
  polaroid: IconPolaroid,
  // music & comms
  music: IconMusic,
  microphone: IconMicrophone,
  headphones: IconHeadphones,
  speakerphone: IconSpeakerphone,
  piano: IconPiano,
  "guitar-pick": IconGuitarPick,
  bell: IconBell,
  "school-bell": IconSchoolBell,
  message: IconMessage,
  mail: IconMail,
  phone: IconPhone,
  volume: IconVolume,
  // health & misc
  stethoscope: IconStethoscope,
  thermometer: IconThermometer,
  lifebuoy: IconLifebuoy,
  lighter: IconLighter,
  sword: IconSword,
  shirt: IconShirt,
  sunglasses: IconSunglasses,
  umbrella: IconUmbrella,
  "thumb-up": IconThumbUp,
  puzzle: IconPuzzle,
  planet: IconPlanet,
  // chart & ui
  "chart-bar": IconChartBar,
  "chart-line": IconChartLine,
  download: IconDownload,
  refresh: IconRefresh,
  settings: IconSettings,
  "zoom-in": IconZoomIn,
  // food & drink (expanded)
  avocado: IconAvocado,
  baguette: IconBaguette,
  beer: IconBeer,
  bone: IconBone,
  bottle: IconBottle,
  "bowl-chopsticks": IconBowlChopsticks,
  "bowl-spoon": IconBowlSpoon,
  bowl: IconBowl,
  bread: IconBread,
  "bubble-tea-2": IconBubbleTea2,
  "bubble-tea": IconBubbleTea,
  "cake-roll": IconCakeRoll,
  carambola: IconCarambola,
  cooker: IconCooker,
  "dog-bowl": IconDogBowl,
  dumpling: IconDumpling,
  "egg-cracked": IconEggCracked,
  "egg-fried": IconEggFried,
  eggs: IconEggs,
  "glass-champagne": IconGlassChampagne,
  "glass-cocktail": IconGlassCocktail,
  "glass-full": IconGlassFull,
  "glass-gin": IconGlassGin,
  glass: IconGlass,
  "grill-fork": IconGrillFork,
  "grill-spatula": IconGrillSpatula,
  grill: IconGrill,
  "ice-cream-2": IconIceCream2,
  "lemon-2": IconLemon2,
  lollipop: IconLollipop,
  melon: IconMelon,
  "michelin-bib-gourmand": IconMichelinBibGourmand,
  "michelin-star-green": IconMichelinStarGreen,
  "michelin-star": IconMichelinStar,
  microwave: IconMicrowave,
  milkshake: IconMilkshake,
  mushroom: IconMushroom,
  nut: IconNut,
  salt: IconSalt,
  sausage: IconSausage,
  "tools-kitchen-2": IconToolsKitchen2,
  "tools-kitchen-3": IconToolsKitchen3,
  "tools-kitchen": IconToolsKitchen,
  wheat: IconWheat,
  whisk: IconWhisk,
  // shopping & commerce (expanded)
  "basket-bolt": IconBasketBolt,
  "basket-cancel": IconBasketCancel,
  "basket-check": IconBasketCheck,
  "basket-code": IconBasketCode,
  "basket-cog": IconBasketCog,
  "basket-discount": IconBasketDiscount,
  "basket-dollar": IconBasketDollar,
  "basket-down": IconBasketDown,
  "basket-exclamation": IconBasketExclamation,
  "basket-heart": IconBasketHeart,
  "basket-minus": IconBasketMinus,
  "basket-pause": IconBasketPause,
  "basket-pin": IconBasketPin,
  "basket-plus": IconBasketPlus,
  "basket-question": IconBasketQuestion,
  "basket-search": IconBasketSearch,
  "basket-share": IconBasketShare,
  "basket-star": IconBasketStar,
  "basket-up": IconBasketUp,
  "basket-x": IconBasketX,
  basket: IconBasket,
  businessplan: IconBusinessplan,
  "cash-banknote-edit": IconCashBanknoteEdit,
  "cash-banknote-heart": IconCashBanknoteHeart,
  "cash-banknote-minus": IconCashBanknoteMinus,
  "cash-banknote-move-back": IconCashBanknoteMoveBack,
  "cash-banknote-move": IconCashBanknoteMove,
  "cash-banknote-plus": IconCashBanknotePlus,
  "cash-banknote": IconCashBanknote,
  "cash-edit": IconCashEdit,
  "cash-heart": IconCashHeart,
  "cash-minus": IconCashMinus,
  "cash-move-back": IconCashMoveBack,
  "cash-move": IconCashMove,
  "cash-plus": IconCashPlus,
  "cash-register": IconCashRegister,
  "clothes-rack": IconClothesRack,
  "coin-bitcoin": IconCoinBitcoin,
  "coin-euro": IconCoinEuro,
  "coin-monero": IconCoinMonero,
  "coin-pound": IconCoinPound,
  "coin-rupee": IconCoinRupee,
  "coin-taka": IconCoinTaka,
  "coin-yen": IconCoinYen,
  "coin-yuan": IconCoinYuan,
  coins: IconCoins,
  "credit-card-hand": IconCreditCardHand,
  "credit-card-pay": IconCreditCardPay,
  "credit-card-refund": IconCreditCardRefund,
  diaper: IconDiaper,
  discount: IconDiscount,
  "e-passport": IconEPassport,
  "flip-flops": IconFlipFlops,
  "gift-card": IconGiftCard,
  hanger: IconHanger,
  jacket: IconJacket,
  "moneybag-edit": IconMoneybagEdit,
  "moneybag-heart": IconMoneybagHeart,
  "moneybag-minus": IconMoneybagMinus,
  "moneybag-move-back": IconMoneybagMoveBack,
  "moneybag-move": IconMoneybagMove,
  "moneybag-plus": IconMoneybagPlus,
  moneybag: IconMoneybag,
  perfume: IconPerfume,
  "receipt-bitcoin": IconReceiptBitcoin,
  "receipt-euro": IconReceiptEuro,
  "receipt-pound": IconReceiptPound,
  "receipt-rupee": IconReceiptRupee,
  "receipt-yen": IconReceiptYen,
  "receipt-yuan": IconReceiptYuan,
  // vehicles & transport (expanded)
  "aerial-lift": IconAerialLift,
  "air-balloon": IconAirBalloon,
  ambulance: IconAmbulance,
  "automatic-gearbox": IconAutomaticGearbox,
  backhoe: IconBackhoe,
  "battery-automotive": IconBatteryAutomotive,
  bike: IconBike,
  bulldozer: IconBulldozer,
  "bus-stop": IconBusStop,
  camper: IconCamper,
  "car-4wd": IconCar4wd,
  "car-crane": IconCarCrane,
  "car-crash": IconCarCrash,
  "car-fan-1": IconCarFan1,
  "car-fan-2": IconCarFan2,
  "car-fan-3": IconCarFan3,
  "car-fan-auto": IconCarFanAuto,
  "car-fan": IconCarFan,
  "car-off-road": IconCarOffRoad,
  "car-suspension": IconCarSuspension,
  "car-suv": IconCarSuv,
  "car-turbine": IconCarTurbine,
  caravan: IconCaravan,
  "charging-pile": IconChargingPile,
  crane: IconCrane,
  engine: IconEngine,
  ferry: IconFerry,
  firetruck: IconFiretruck,
  forklift: IconForklift,
  "garden-cart": IconGardenCart,
  "gas-station": IconGasStation,
  "helicopter-landing": IconHelicopterLanding,
  helicopter: IconHelicopter,
  jetski: IconJetski,
  moped: IconMoped,
  // health & wellbeing
  accessible: IconAccessible,
  "activity-heartbeat": IconActivityHeartbeat,
  activity: IconActivity,
  "baby-bottle": IconBabyBottle,
  "baby-carriage": IconBabyCarriage,
  bandage: IconBandage,
  blind: IconBlind,
  braille: IconBraille,
  brain: IconBrain,
  cane: IconCane,
  "checkup-list": IconCheckupList,
  crutches: IconCrutches,
  deaf: IconDeaf,
  dental: IconDental,
  "disabled-2": IconDisabled2,
  disabled: IconDisabled,
  "dna-2": IconDna2,
  ear: IconEar,
  "emergency-bed": IconEmergencyBed,
  empathize: IconEmpathize,
  "eye-bitcoin": IconEyeBitcoin,
  "eye-discount": IconEyeDiscount,
  "eye-dotted": IconEyeDotted,
  "eye-table": IconEyeTable,
  "eyeglass-2": IconEyeglass2,
  eyeglass: IconEyeglass,
  "face-mask": IconFaceMask,
  fall: IconFall,
  "fingerprint-scan": IconFingerprintScan,
  "first-aid-kit": IconFirstAidKit,
  // nature & plants (expanded)
  alien: IconAlien,
  "atom-2": IconAtom2,
  cactus: IconCactus,
  cannabis: IconCannabis,
  "clover-2": IconClover2,
  clover: IconClover,
  "crystal-ball": IconCrystalBall,
  "drop-circle": IconDropCircle,
  droplets: IconDroplets,
  growth: IconGrowth,
  iceberg: IconIceberg,
  "leaf-2": IconLeaf2,
  meteor: IconMeteor,
  "plant-2": IconPlant2,
  ripple: IconRipple,
  seedling: IconSeedling,
  snowman: IconSnowman,
  "sun-electricity": IconSunElectricity,
  "wind-electricity": IconWindElectricity,
  // weather (expanded)
  "cloud-bolt": IconCloudBolt,
  "cloud-cancel": IconCloudCancel,
  "cloud-check": IconCloudCheck,
  "cloud-code": IconCloudCode,
  "cloud-cog": IconCloudCog,
  "cloud-dollar": IconCloudDollar,
  "cloud-down": IconCloudDown,
  "cloud-exclamation": IconCloudExclamation,
  "cloud-fog": IconCloudFog,
  "cloud-heart": IconCloudHeart,
  "cloud-minus": IconCloudMinus,
  "cloud-pause": IconCloudPause,
  "cloud-pin": IconCloudPin,
  "cloud-plus": IconCloudPlus,
  "cloud-question": IconCloudQuestion,
  "cloud-rain": IconCloudRain,
  "cloud-search": IconCloudSearch,
  "cloud-share": IconCloudShare,
  "cloud-snow": IconCloudSnow,
  "cloud-star": IconCloudStar,
  "cloud-storm": IconCloudStorm,
  "cloud-up": IconCloudUp,
  "cloud-x": IconCloudX,
  comet: IconComet,
  flare: IconFlare,
  // animals (expanded)
  bat: IconBat,
  "fish-bone": IconFishBone,
  "fish-hook": IconFishHook,
  horseshoe: IconHorseshoe,
  "pig-money": IconPigMoney,
  spider: IconSpider,
  // places & map
  "air-traffic-control": IconAirTrafficControl,
  beach: IconBeach,
  campfire: IconCampfire,
  "current-location": IconCurrentLocation,
  directions: IconDirections,
  "escalator-down": IconEscalatorDown,
  "escalator-up": IconEscalatorUp,
  escalator: IconEscalator,
  "fire-hydrant": IconFireHydrant,
  "flag-2": IconFlag2,
  "flag-3": IconFlag3,
  "flag-bolt": IconFlagBolt,
  "flag-cancel": IconFlagCancel,
  "flag-check": IconFlagCheck,
  "flag-code": IconFlagCode,
  "flag-cog": IconFlagCog,
  "flag-dollar": IconFlagDollar,
  "flag-down": IconFlagDown,
  "flag-exclamation": IconFlagExclamation,
  "flag-heart": IconFlagHeart,
  "flag-minus": IconFlagMinus,
  "flag-pause": IconFlagPause,
  "flag-pin": IconFlagPin,
  "flag-plus": IconFlagPlus,
  "flag-question": IconFlagQuestion,
};

export const TABLER_ICON_KEYS = Object.keys(TABLER_ICONS);

/**
 * Native grouping of the Tabler catalog, lifted from the section comments
 * inside {@link TABLER_ICONS} (e.g. `// food & drink`). The catalog above is
 * the single source of truth for membership; this array only attaches a
 * Persian label to each existing group. Keep it in sync if you reorder the
 * catalog. Used by the icon picker's category-tab navigation. Brand icons
 * carry their own `category` field in ICON_REGISTRY and are tabbed
 * separately; these groups cover the generic icons.
 */
export type TablerIconGroup = {
  /** Stable id used as the tab value. */
  id: string;
  /** Persian tab label. */
  label: string;
  /** Member Tabler keys (without the `t:` prefix). */
  keys: string[];
};

export const TABLER_ICON_GROUPS: TablerIconGroup[] = [
  {
    id: "symbols",
    label: "نمادها",
    keys: [
      "rocket", "heart", "star", "bolt", "bulb", "sparkles", "flame",
      "fire-extinguisher", "rainbow", "infinity", "diamond", "crown",
      "trophy", "target", "flag", "bookmark", "pin", "link", "world",
      "globe", "search", "eye", "key", "lock", "shield", "ghost", "ufo",
      "robot", "atom", "dna", "yin-yang", "confetti", "sticker", "balloon",
      "gift", "christmas-tree",
    ],
  },
  {
    id: "people",
    label: "افراد و حیوانات",
    keys: [
      "user", "users", "smile", "baby", "cat", "dog", "paw", "fish", "deer",
      "horse", "pig", "butterfly", "feather", "leaf", "plant", "plant2",
      "tree", "flower", "mountain", "sun", "moon", "sunrise", "cloud",
      "snowflake", "wind", "droplet",
    ],
  },
  {
    id: "food",
    label: "خوراکی و نوشیدنی",
    keys: [
      "apple", "cake", "candy", "cookie", "carrot", "cheese", "chef-hat",
      "cherry", "egg", "lemon", "meat", "pepper", "salad", "soup", "pizza",
      "burger", "ice-cream", "milk", "mug", "cup", "coffee", "teapot",
    ],
  },
  {
    id: "activity",
    label: "ورزش و سفر",
    keys: [
      "basketball", "football", "tennis", "volleyball", "baseball",
      "swimming", "yoga", "chess", "dice", "plane", "train", "car",
      "motorbike", "ship", "sailboat", "bus", "truck", "road", "anchor",
      "parachute", "drone", "luggage", "backpack",
    ],
  },
  {
    id: "shopping",
    label: "خرید و مالی",
    keys: [
      "shopping-bag", "shopping-cart", "paper-bag", "tag", "ticket",
      "credit-card", "wallet", "coin", "cash", "package",
    ],
  },
  {
    id: "tools",
    label: "ابزار و خانه",
    keys: [
      "hammer", "tools", "scissors", "ruler", "paint", "palette", "spray",
      "magnet", "flask", "microscope", "telescope", "compass", "map",
      "home", "building", "school", "door", "bed", "sofa", "table",
    ],
  },
  {
    id: "tech",
    label: "فناوری و دستگاه",
    keys: [
      "laptop", "mobile", "tv", "watch", "devices", "camera", "photo",
      "video", "qrcode", "keyboard", "server", "database", "terminal",
      "code", "printer", "plug", "wifi",
    ],
  },
  {
    id: "office",
    label: "کار و دفتر",
    keys: [
      "calendar", "clock", "alarm", "hourglass", "briefcase", "folder",
      "file", "notebook", "book", "pencil", "edit", "clipboard",
      "paperclip", "archive", "inbox", "news", "presentation", "podium",
      "polaroid",
    ],
  },
  {
    id: "media",
    label: "موسیقی و ارتباط",
    keys: [
      "music", "microphone", "headphones", "speakerphone", "piano",
      "guitar-pick", "bell", "school-bell", "message", "mail", "phone",
      "volume",
    ],
  },
  {
    id: "misc",
    label: "متفرقه",
    keys: [
      "stethoscope", "thermometer", "lifebuoy", "lighter", "sword", "shirt",
      "sunglasses", "umbrella", "thumb-up", "puzzle", "planet", "chart-bar",
      "chart-line", "download", "refresh", "settings", "zoom-in",
    ],
  },
  {
    id: "food2",
    label: "خوراکی و نوشیدنی (بیشتر)",
    keys: [
      "avocado", "baguette", "beer", "bone", "bottle", "bowl-chopsticks",
      "bowl-spoon", "bowl", "bread", "bubble-tea-2", "bubble-tea",
      "cake-roll", "carambola", "cooker", "dog-bowl", "dumpling",
      "egg-cracked", "egg-fried", "eggs", "glass-champagne",
      "glass-cocktail", "glass-full", "glass-gin", "glass", "grill-fork",
      "grill-spatula", "grill", "ice-cream-2", "lemon-2", "lollipop",
      "melon", "michelin-bib-gourmand", "michelin-star-green",
      "michelin-star", "microwave", "milkshake", "mushroom", "nut", "salt",
      "sausage", "tools-kitchen-2", "tools-kitchen-3", "tools-kitchen",
      "wheat", "whisk",
    ],
  },
  {
    id: "shopping2",
    label: "فروشگاه و مالی (بیشتر)",
    keys: [
      "basket-bolt", "basket-cancel", "basket-check", "basket-code",
      "basket-cog", "basket-discount", "basket-dollar", "basket-down",
      "basket-exclamation", "basket-heart", "basket-minus", "basket-pause",
      "basket-pin", "basket-plus", "basket-question", "basket-search",
      "basket-share", "basket-star", "basket-up", "basket-x", "basket",
      "businessplan", "cash-banknote-edit", "cash-banknote-heart",
      "cash-banknote-minus", "cash-banknote-move-back", "cash-banknote-move",
      "cash-banknote-plus", "cash-banknote", "cash-edit", "cash-heart",
      "cash-minus", "cash-move-back", "cash-move", "cash-plus",
      "cash-register", "clothes-rack", "coin-bitcoin", "coin-euro",
      "coin-monero", "coin-pound", "coin-rupee", "coin-taka", "coin-yen",
      "coin-yuan", "coins", "credit-card-hand", "credit-card-pay",
      "credit-card-refund", "diaper", "discount", "e-passport", "flip-flops",
      "gift-card", "hanger", "jacket", "moneybag-edit", "moneybag-heart",
      "moneybag-minus", "moneybag-move-back", "moneybag-move",
      "moneybag-plus", "moneybag", "perfume", "receipt-bitcoin",
      "receipt-euro", "receipt-pound", "receipt-rupee", "receipt-yen",
      "receipt-yuan",
    ],
  },
  {
    id: "vehicles2",
    label: "وسایل نقلیه (بیشتر)",
    keys: [
      "aerial-lift", "air-balloon", "ambulance", "automatic-gearbox",
      "backhoe", "battery-automotive", "bike", "bulldozer", "bus-stop",
      "camper", "car-4wd", "car-crane", "car-crash", "car-fan-1",
      "car-fan-2", "car-fan-3", "car-fan-auto", "car-fan", "car-off-road",
      "car-suspension", "car-suv", "car-turbine", "caravan", "charging-pile",
      "crane", "engine", "ferry", "firetruck", "forklift", "garden-cart",
      "gas-station", "helicopter-landing", "helicopter", "jetski", "moped",
    ],
  },
  {
    id: "health",
    label: "سلامت و درمان",
    keys: [
      "accessible", "activity-heartbeat", "activity", "baby-bottle",
      "baby-carriage", "bandage", "blind", "braille", "brain", "cane",
      "checkup-list", "crutches", "deaf", "dental", "disabled-2", "disabled",
      "dna-2", "ear", "emergency-bed", "empathize", "eye-bitcoin",
      "eye-discount", "eye-dotted", "eye-table", "eyeglass-2", "eyeglass",
      "face-mask", "fall", "fingerprint-scan", "first-aid-kit",
    ],
  },
  {
    id: "nature2",
    label: "طبیعت (بیشتر)",
    keys: [
      "alien", "atom-2", "cactus", "cannabis", "clover-2", "clover",
      "crystal-ball", "drop-circle", "droplets", "growth", "iceberg",
      "leaf-2", "meteor", "plant-2", "ripple", "seedling", "snowman",
      "sun-electricity", "wind-electricity",
    ],
  },
  {
    id: "weather2",
    label: "آب‌وهوا (بیشتر)",
    keys: [
      "cloud-bolt", "cloud-cancel", "cloud-check", "cloud-code", "cloud-cog",
      "cloud-dollar", "cloud-down", "cloud-exclamation", "cloud-fog",
      "cloud-heart", "cloud-minus", "cloud-pause", "cloud-pin", "cloud-plus",
      "cloud-question", "cloud-rain", "cloud-search", "cloud-share",
      "cloud-snow", "cloud-star", "cloud-storm", "cloud-up", "cloud-x",
      "comet", "flare",
    ],
  },
  {
    id: "animals2",
    label: "حیوانات (بیشتر)",
    keys: [
      "bat", "fish-bone", "fish-hook", "horseshoe", "pig-money", "spider",
    ],
  },
  {
    id: "places",
    label: "مکان و نقشه",
    keys: [
      "air-traffic-control", "beach", "campfire", "current-location",
      "directions", "escalator-down", "escalator-up", "escalator",
      "fire-hydrant", "flag-2", "flag-3", "flag-bolt", "flag-cancel",
      "flag-check", "flag-code", "flag-cog", "flag-dollar", "flag-down",
      "flag-exclamation", "flag-heart", "flag-minus", "flag-pause",
      "flag-pin", "flag-plus", "flag-question",
    ],
  },
];

/**
 * Persian search aliases for common icons. Allows users to find icons by
 * typing the Farsi term (e.g. "سگ" → dog). Each entry maps a Tabler key
 * (without the `t:` prefix) to one or more Persian search tokens.
 */
export const TABLER_ICON_ALIASES: Record<string, string> = {
  alarm: "ساعت زنگدار آلارم",
  anchor: "لنگر کشتی",
  apple: "سیب میوه",
  archive: "آرشیو بایگانی",
  atom: "اتم علم",
  "baby-carriage": "کالسکه بچه نوزاد",
  backpack: "کوله پشتی",
  "ball-basketball": "بسکتبال توپ",
  "ball-baseball": "بیسبال توپ",
  "ball-football": "فوتبال توپ",
  "ball-tennis": "تنیس توپ",
  "ball-volleyball": "والیبال توپ",
  balloon: "بادکنک",
  bed: "تخت خواب",
  bell: "زنگ ناقوس",
  bolt: "برق صاعقه رعد",
  book: "کتاب",
  bookmark: "نشان نشانک",
  briefcase: "کیف اداری",
  building: "ساختمان",
  bulb: "لامپ ایده",
  burger: "برگر همبرگر",
  bus: "اتوبوس",
  butterfly: "پروانه",
  cake: "کیک تولد",
  calendar: "تقویم",
  camera: "دوربین",
  candy: "آب نبات",
  car: "ماشین خودرو اتومبیل",
  carrot: "هویج",
  cash: "پول نقد",
  cat: "گربه",
  "chart-bar": "نمودار میله ای",
  "chart-line": "نمودار خطی",
  cheese: "پنیر",
  "chef-hat": "آشپز کلاه",
  cherry: "گیلاس آلبالو",
  chess: "شطرنج",
  "christmas-tree": "درخت کریسمس",
  clipboard: "کلیپبورد",
  clock: "ساعت",
  cloud: "ابر",
  code: "کد برنامه نویسی",
  coffee: "قهوه",
  coin: "سکه پول",
  compass: "قطب نما",
  confetti: "جشن کاغذ رنگی",
  cookie: "کوکی شیرینی",
  "credit-card": "کارت اعتباری بانکی",
  crown: "تاج پادشاه",
  cup: "فنجان لیوان",
  database: "پایگاه داده",
  deer: "گوزن",
  "device-laptop": "لپ تاپ",
  "device-mobile": "موبایل گوشی",
  "device-tv": "تلویزیون",
  "device-watch": "ساعت مچی",
  diamond: "الماس جواهر",
  dog: "سگ",
  donut: "دونات",
  download: "دانلود",
  drone: "پهپاد",
  edit: "ویرایش",
  egg: "تخم مرغ",
  "fire-extinguisher": "کپسول آتش نشانی",
  fire: "آتش شعله",
  fish: "ماهی",
  flag: "پرچم",
  flame: "آتش شعله",
  flask: "بشر آزمایش",
  flower: "گل",
  gift: "هدیه کادو",
  globe: "کره زمین جهان",
  glass: "لیوان نوشیدنی",
  grill: "کباب پز",
  "guitar-pick": "گیتار مضراب",
  hammer: "چکش",
  hanger: "چوب لباسی",
  headphones: "هدفون",
  heart: "قلب عشق",
  helmet: "کلاه ایمنی",
  home: "خانه منزل",
  horseshoe: "نعل اسب",
  hotel: "هتل",
  "ice-cream": "بستنی",
  inbox: "اینباکس صندوق ورودی",
  jacket: "ژاکت کاپشن",
  key: "کلید",
  knife: "چاقو",
  laptop: "لپ تاپ",
  leaf: "برگ",
  lifebuoy: "نجات غریق حلقه",
  lighter: "فندک",
  lock: "قفل",
  mail: "ایمیل نامه پست",
  map: "نقشه",
  message: "پیام چت",
  microphone: "میکروفون",
  moon: "ماه شب",
  motorbike: "موتور سیکلت",
  mountain: "کوه",
  mouse: "موس",
  music: "موسیقی آهنگ",
  "map-pin": "پین نقشه مکان",
  news: "خبر روزنامه",
  notebook: "دفترچه دفتر",
  package: "بسته",
  paint: "نقاشی رنگ",
  paperclip: "گیره کاغذ",
  pencil: "مداد",
  phone: "تلفن تماس",
  piano: "پیانو",
  "pin-map": "پین نقشه",
  pizza: "پیتزا",
  plane: "هواپیما",
  planet: "سیاره",
  plant: "گیاه",
  podium: "سکو",
  polaroid: "پلاروید عکس",
  presentation: "ارائه پرزنتیشن",
  printer: "پرینتر چاپگر",
  puzzle: "پازل",
  refresh: "بروزرسانی",
  rocket: "موشک راکت",
  rose: "گل رز",
  scissors: "قیچی",
  "school-bell": "زنگ مدرسه",
  search: "جستجو سرچ",
  settings: "تنظیمات",
  shield: "سپر",
  ship: "کشتی",
  shirt: "پیراهن لباس",
  shoe: "کفش",
  shopping: "خرید فروشگاه",
  "shopping-bag": "کیف خرید فروشگاه",
  "shopping-cart": "سبد خرید",
  smile: "لبخند خنده",
  snowflake: "دانه برف",
  speakerphone: "بلندگو",
  star: "ستاره",
  stethoscope: "گوشی پزشکی",
  sun: "خورشید آفتاب",
  sunglasses: "عینک آفتابی",
  sushi: "سوشی",
  sword: "شمشیر",
  "tea-bag": "چای",
  "thumb-up": "لایک پسند",
  thermometer: "دماسنج",
  tools: "ابزار",
  truck: "کامیون",
  trophy: "جام قهرمانی",
  umbrella: "چتر",
  user: "کاربر شخص نفر",
  users: "کاربران مردم",
  video: "ویدیو فیلم",
  volume: "صدا بلندی",
  wallet: "کیف پول",
  whirl: "گردباد",
  "wind-turbine": "توربین بادی",
  wine: "شراب",
  yoga: "یوگا",
  "zoom-in": "زوم بزرگنمایی",
};

const TABLER_PREFIX = "t:";

export function isTablerIconKey(value: unknown): value is string {
  return (
    typeof value === "string" &&
    value.startsWith(TABLER_PREFIX) &&
    value.slice(TABLER_PREFIX.length) in TABLER_ICONS
  );
}

export function tablerKeyOf(name: string): string {
  return `${TABLER_PREFIX}${name}`;
}

export function tablerNameOf(key: string): string | null {
  if (!key.startsWith(TABLER_PREFIX)) return null;
  return key.slice(TABLER_PREFIX.length);
}

export function getTablerIcon(key: string): TablerIconComponent | null {
  const name = tablerNameOf(key);
  if (!name) return null;
  return TABLER_ICONS[name] ?? null;
}
