/**
 * Phase 12 — `POST /api/billing/invoices/[invoiceId]/pay`.
 *
 * Initiates a Zarinpal payment for an *existing* unpaid invoice. The use
 * case is invoices generated by the daily billing cron on trial-end
 * (Phase 7) — those rows are inserted with `status='unpaid'` and no
 * authority. This endpoint:
 *
 *   1. Loads the invoice, asserts it's owned by the caller.
 *   2. Rejects anything other than `status='unpaid'` (paid/expired/canceled
 *      are terminal — the user has to start a new checkout).
 *   3. Calls `requestPayment` with the invoice total + a fresh callback URL
 *      pointing back at `/api/billing/callback?invoice={id}`.
 *   4. Inserts a fresh `payments` row carrying the new authority and
 *      returns the gateway redirect URL.
 *
 * One invoice can have many payment attempts (the previous attempt may
 * have failed mid-redirect or expired); callback handler is idempotent
 * via `payments.authority` UNIQUE.
 */
import { eq } from "drizzle-orm";
import { NextResponse } from "next/server";

import { getDb } from "@/db";
import { invoices, payments } from "@/db/schema";
import { requireUser } from "@/lib/auth/session";
import { log } from "@/lib/log";
import { absoluteUrl } from "@/lib/site";
import { requestPayment } from "@/lib/zarinpal";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

export async function POST(
  _request: Request,
  { params }: { params: Promise<{ invoiceId: string }> },
) {
  const viewer = await requireUser();
  const { invoiceId } = await params;

  const db = getDb();
  const invoice = await db.query.invoices.findFirst({
    where: eq(invoices.id, invoiceId),
    with: { plan: true },
  });

  if (!invoice) {
    return NextResponse.json({ error: "not_found" }, { status: 404 });
  }
  if (invoice.userId !== viewer.user.id) {
    return NextResponse.json({ error: "forbidden" }, { status: 403 });
  }
  if (invoice.status !== "unpaid") {
    return NextResponse.json(
      { error: "invoice_not_payable", message: "این فاکتور قابل پرداخت نیست." },
      { status: 409 },
    );
  }
  if (invoice.totalToman <= 0) {
    // Defensive: an unpaid invoice with zero total shouldn't exist (free
    // path marks paid in the same TX). Surface as a hard error rather
    // than silently flipping it.
    return NextResponse.json(
      { error: "invoice_not_payable", message: "مبلغ فاکتور صفر است." },
      { status: 409 },
    );
  }

  const description = `${invoice.plan.nameFa} — ${
    invoice.billingCycle === "annual" ? "اشتراک سالانه" : "اشتراک ماهانه"
  } — ${invoice.number}`;

  let zarinpal;
  try {
    zarinpal = await requestPayment({
      amountToman: invoice.totalToman,
      callbackUrl: absoluteUrl(
        `/api/billing/callback?invoice=${invoice.id}`,
      ),
      description,
      mobile: viewer.user.phone.startsWith("98")
        ? `0${viewer.user.phone.slice(2)}`
        : viewer.user.phone,
      metadata: {
        invoice: invoice.number,
        page_id: invoice.pageId,
        plan_key: invoice.plan.key,
        cycle: invoice.billingCycle,
      },
    });
  } catch (err) {
    log.warn("billing.invoice_pay.zarinpal_request_failed", {
      invoiceId: invoice.id,
      error: (err as Error).message,
    });
    return NextResponse.json(
      {
        error: "gateway_unavailable",
        message: "ارتباط با درگاه پرداخت برقرار نشد.",
      },
      { status: 502 },
    );
  }

  await db.insert(payments).values({
    invoiceId: invoice.id,
    provider: "zarinpal",
    authority: zarinpal.authority,
    amountToman: invoice.totalToman,
    status: "initiated",
  });

  return NextResponse.json({
    ok: true,
    redirectUrl: zarinpal.redirectUrl,
  });
}
