/**
 * scripts/seed-categories.ts
 *
 * Insert-only seeder for the two-level taxonomy (industries → categories).
 *
 * Reads `scripts/data/categories-seed.json` (committed source of truth,
 * generated by `scripts/build-categories-seed.ts`) and upserts into the
 * `industries` and `categories` tables.
 *
 * Run after a fresh DB or whenever you want to top up new rows added to
 * the seed JSON without re-running the SQL migration:
 *
 *   npm run db:seed:categories
 *
 * Behavior contract:
 *   - If an industry / category does NOT exist (by slug), INSERT it.
 *   - If a row already exists, LEAVE IT ALONE. This means admin edits made
 *     in /admin/categories survive future seed runs. To force a refresh,
 *     run the script with `--force` (overwrites titleFa/titleEn/iconKey/
 *     sortOrder/accountType[s]; does NOT change isActive so deactivations
 *     stick).
 *   - This script never DELETEs anything.
 *
 * Note: the 0046 migration already seeds everything, so on a fresh DB
 * after `npm run db:migrate`, this script is a no-op. It exists primarily
 * for dev workflow (running the JSON's contents into a partially-seeded
 * DB) and for the rare case where you want to add a single new category
 * to the JSON and ship it without writing a one-off SQL migration.
 */

import "dotenv/config";
import { readFileSync } from "node:fs";
import path from "node:path";

import { eq } from "drizzle-orm";
import { drizzle } from "drizzle-orm/postgres-js";
import postgres from "postgres";

import * as schema from "../src/db/schema";

type IndustrySeed = {
  slug: string;
  titleFa: string;
  titleEn: string;
  iconKey: string;
  accountTypes: string[];
  sortOrder: number;
};

type CategorySeed = {
  industrySlug: string;
  slug: string;
  titleFa: string;
  titleEn: string;
  iconKey: string;
  accountType: string;
  sortOrder: number;
};

type SeedFile = {
  industries: IndustrySeed[];
  categories: CategorySeed[];
};

async function main() {
  const force = process.argv.includes("--force");
  const dbUrl = process.env.DATABASE_URL;
  if (!dbUrl) {
    console.error("DATABASE_URL is not set. Aborting.");
    process.exit(1);
  }

  const seedPath = path.resolve(__dirname, "data", "categories-seed.json");
  const raw = readFileSync(seedPath, "utf8");
  const seed = JSON.parse(raw) as SeedFile;

  const client = postgres(dbUrl, { max: 1 });
  const db = drizzle(client, { schema });

  let industriesInserted = 0;
  let industriesUpdated = 0;
  let industriesSkipped = 0;
  let categoriesInserted = 0;
  let categoriesUpdated = 0;
  let categoriesSkipped = 0;

  try {
    // ── Industries ────────────────────────────────────────────────────────
    const existingIndustries = await db.select().from(schema.industries);
    const industryBySlug = new Map(
      existingIndustries.map((i) => [i.slug, i] as const),
    );

    for (const row of seed.industries) {
      const current = industryBySlug.get(row.slug);
      if (!current) {
        await db.insert(schema.industries).values({
          slug: row.slug,
          titleFa: row.titleFa,
          titleEn: row.titleEn,
          iconKey: row.iconKey,
          accountTypes: row.accountTypes,
          sortOrder: row.sortOrder,
          isActive: true,
        });
        industriesInserted++;
      } else if (force) {
        await db
          .update(schema.industries)
          .set({
            titleFa: row.titleFa,
            titleEn: row.titleEn,
            iconKey: row.iconKey,
            accountTypes: row.accountTypes,
            sortOrder: row.sortOrder,
            updatedAt: new Date(),
          })
          .where(eq(schema.industries.id, current.id));
        industriesUpdated++;
      } else {
        industriesSkipped++;
      }
    }

    // Re-fetch so we have IDs for newly-inserted industries.
    const refreshedIndustries = await db.select().from(schema.industries);
    const industryIdBySlug = new Map(
      refreshedIndustries.map((i) => [i.slug, i.id] as const),
    );

    // ── Categories ────────────────────────────────────────────────────────
    const existingCategories = await db.select().from(schema.categories);
    const categoryBySlug = new Map(
      existingCategories.map((c) => [c.slug, c] as const),
    );

    for (const row of seed.categories) {
      const industryId = industryIdBySlug.get(row.industrySlug);
      if (!industryId) {
        console.warn(
          `Skipping category '${row.slug}': industry '${row.industrySlug}' not found`,
        );
        continue;
      }
      const current = categoryBySlug.get(row.slug);
      if (!current) {
        await db.insert(schema.categories).values({
          industryId,
          slug: row.slug,
          titleFa: row.titleFa,
          titleEn: row.titleEn,
          iconKey: row.iconKey,
          accountType: row.accountType,
          sortOrder: row.sortOrder,
          isActive: true,
        });
        categoriesInserted++;
      } else if (force) {
        await db
          .update(schema.categories)
          .set({
            industryId,
            titleFa: row.titleFa,
            titleEn: row.titleEn,
            iconKey: row.iconKey,
            accountType: row.accountType,
            sortOrder: row.sortOrder,
            updatedAt: new Date(),
          })
          .where(eq(schema.categories.id, current.id));
        categoriesUpdated++;
      } else {
        categoriesSkipped++;
      }
    }
  } finally {
    await client.end();
  }

  console.log("Industries:", {
    inserted: industriesInserted,
    updated: industriesUpdated,
    skipped: industriesSkipped,
  });
  console.log("Categories:", {
    inserted: categoriesInserted,
    updated: categoriesUpdated,
    skipped: categoriesSkipped,
  });
  if (!force && (industriesSkipped > 0 || categoriesSkipped > 0)) {
    console.log(
      "Tip: rerun with --force to overwrite titles/icons/sort_order for existing rows.",
    );
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
